import { z } from "zod";

const TosuDataSchema = z.object({
  client: z.string(),
  server: z.string(),
  state: z.object({
    number: z.number(),
    name: z.string(),
  }),
  session: z.object({
    playTime: z.number(),
    playCount: z.number(),
  }),
  settings: z.object({
    interfaceVisible: z.boolean(),
    replayUIVisible: z.boolean(),
    chatVisibilityStatus: z.object({
      number: z.number(),
      name: z.string(),
    }),
    leaderboard: z.object({
      visible: z.boolean(),
      type: z.object({
        number: z.number(),
        name: z.string(),
      }),
    }),
    progressBar: z.object({
      number: z.number(),
      name: z.string(),
    }),
    bassDensity: z.number(),
    resolution: z.object({
      fullscreen: z.boolean(),
      width: z.number(),
      height: z.number(),
      widthFullscreen: z.number(),
      heightFullscreen: z.number(),
    }),
    client: z.object({
      updateAvailable: z.boolean(),
      branch: z.number(),
      version: z.string(),
    }),
    scoreMeter: z.object({
      type: z.object({
        number: z.number(),
        name: z.string(),
      }),
      size: z.number(),
    }),
    cursor: z.object({
      useSkinCursor: z.boolean(),
      autoSize: z.boolean(),
      size: z.number(),
      menuSize: z.number(),
    }),
    mouse: z.object({
      rawInput: z.boolean(),
      highPrecision: z.boolean(),
      disableButtons: z.boolean(),
      disableWheel: z.boolean(),
      sensitivity: z.number(),
    }),
    tablet: z.object({
      enabled: z.boolean(),
      x: z.number(),
      y: z.number(),
      width: z.number(),
      height: z.number(),
      rotation: z.number(),
      pressureThreshold: z.number(),
    }),
    mania: z.object({
      speedBPMScale: z.boolean(),
      usePerBeatmapSpeedScale: z.boolean(),
      scrollSpeed: z.number(),
      scrollDirection: z.object({
        number: z.number(),
        name: z.string(),
      }),
    }),
    sort: z.object({
      number: z.number(),
      name: z.string(),
    }),
    group: z.object({
      number: z.number(),
      name: z.string(),
    }),
    skin: z.object({
      useDefaultSkinInEditor: z.boolean(),
      ignoreBeatmapSkins: z.boolean(),
      tintSliderBall: z.boolean(),
      useTaikoSkin: z.boolean(),
      name: z.string(),
    }),
    mode: z.object({
      number: z.number(),
      name: z.string(),
    }),
    audio: z.object({
      ignoreBeatmapSounds: z.boolean(),
      useSkinSamples: z.boolean(),
      volume: z.object({
        masterInactive: z.number(),
        master: z.number(),
        music: z.number(),
        effect: z.number(),
      }),
      offset: z.object({
        universal: z.number(),
      }),
    }),
    background: z.object({
      storyboard: z.boolean(),
      video: z.boolean(),
      blur: z.number(),
      dim: z.number(),
    }),
    keybinds: z.object({
      osu: z.object({
        k1: z.string(),
        k2: z.string(),
        smokeKey: z.string(),
      }),
      fruits: z.object({
        k1: z.string(),
        k2: z.string(),
        Dash: z.string(),
      }),
      taiko: z.object({
        innerLeft: z.string(),
        innerRight: z.string(),
        outerLeft: z.string(),
        outerRight: z.string(),
      }),
      quickRetry: z.string(),
    }),
  }),
  profile: z.object({
    userStatus: z.object({
      number: z.number(),
      name: z.string(),
    }),
    banchoStatus: z.object({
      number: z.number(),
      name: z.string(),
    }),
    id: z.number(),
    name: z.string(),
    mode: z.object({
      number: z.number(),
      name: z.string(),
    }),
    rankedScore: z.number(),
    level: z.number(),
    accuracy: z.number(),
    pp: z.number(),
    playCount: z.number(),
    globalRank: z.number(),
    countryCode: z.object({
      number: z.number(),
      name: z.string(),
    }),
    backgroundColour: z.string(),
  }),
  beatmap: z.object({
    isKiai: z.boolean(),
    isBreak: z.boolean(),
    isConvert: z.boolean(),
    time: z.object({
      live: z.number(),
      firstObject: z.number(),
      lastObject: z.number(),
      mp3Length: z.number(),
    }),
    status: z.object({
      number: z.number(),
      name: z.string(),
    }),
    checksum: z.string(),
    id: z.number(),
    set: z.number(),
    mode: z.object({
      number: z.number(),
      name: z.string(),
    }),
    artist: z.string(),
    artistUnicode: z.string(),
    title: z.string(),
    titleUnicode: z.string(),
    mapper: z.string(),
    version: z.string(),
    stats: z.object({
      stars: z.object({
        live: z.number(),
        aim: z.number().optional(),
        speed: z.number().optional(),
        flashlight: z.number().optional(),
        sliderFactor: z.number().optional(),
        hitWindow: z.number().optional(),
        total: z.number(),
      }),
      ar: z.object({
        original: z.number(),
        converted: z.number(),
      }),
      cs: z.object({
        original: z.number(),
        converted: z.number(),
      }),
      od: z.object({
        original: z.number(),
        converted: z.number(),
      }),
      hp: z.object({
        original: z.number(),
        converted: z.number(),
      }),
      bpm: z.object({
        realtime: z.number(),
        common: z.number(),
        min: z.number(),
        max: z.number(),
      }),
      objects: z.object({
        circles: z.number(),
        sliders: z.number(),
        spinners: z.number(),
        holds: z.number(),
        total: z.number(),
      }),
      maxCombo: z.number(),
    }),
  }),
  play: z.object({
    playerName: z.string(),
    mode: z.object({
      number: z.number(),
      name: z.string(),
    }),
    score: z.number(),
    accuracy: z.number(),
    healthBar: z.object({
      normal: z.number(),
      smooth: z.number(),
    }),
    hits: z.object({
      0: z.number(),
      50: z.number(),
      100: z.number(),
      300: z.number(),
      geki: z.number(),
      katu: z.number(),
      sliderBreaks: z.number(),
      sliderEndHits: z.number(),
      smallTickHits: z.number(),
      largeTickHits: z.number(),
    }),
    hitErrorArray: z.array(z.unknown()),
    combo: z.object({
      current: z.number(),
      max: z.number(),
    }),
    mods: z.object({
      checksum: z.string(),
      number: z.number(),
      name: z.string(),
      array: z.array(z.unknown()),
      rate: z.number(),
    }),
    rank: z.object({
      current: z.string(),
      maxThisPlay: z.string(),
    }),
    pp: z.object({
      current: z.number(),
      fc: z.number(),
      maxAchieved: z.number(),
      maxAchievable: z.number(),
      detailed: z.object({
        current: z.object({
          aim: z.number(),
          speed: z.number(),
          accuracy: z.number(),
          difficulty: z.number(),
          flashlight: z.number(),
          total: z.number(),
        }),
        fc: z.object({
          aim: z.number(),
          speed: z.number(),
          accuracy: z.number(),
          difficulty: z.number(),
          flashlight: z.number(),
          total: z.number(),
        }),
      }),
    }),
    unstableRate: z.number(),
  }),
  leaderboard: z.array(z.unknown()),
  performance: z.object({
    accuracy: z.object({
      90: z.number(),
      91: z.number(),
      92: z.number(),
      93: z.number(),
      94: z.number(),
      95: z.number(),
      96: z.number(),
      97: z.number(),
      98: z.number(),
      99: z.number(),
      100: z.number(),
    }),
    graph: z.object({
      series: z.array(
        z.object({
          name: z.string(),
          data: z.array(z.number()),
        }),
      ),
      xaxis: z.array(z.number()),
    }),
  }),
  resultsScreen: z.object({
    scoreId: z.number(),
    playerName: z.string(),
    mode: z.object({
      number: z.number(),
      name: z.string(),
    }),
    score: z.number(),
    accuracy: z.number(),
    name: z.string(),
    hits: z.object({
      0: z.number(),
      50: z.number(),
      100: z.number(),
      300: z.number(),
      geki: z.number(),
      katu: z.number(),
      sliderEndHits: z.number(),
      smallTickHits: z.number(),
      largeTickHits: z.number(),
    }),
    mods: z.object({
      checksum: z.string(),
      number: z.number(),
      name: z.string(),
      array: z.array(z.unknown()),
      rate: z.number(),
    }),
    maxCombo: z.number(),
    rank: z.string(),
    pp: z.object({
      current: z.number(),
      fc: z.number(),
    }),
    createdAt: z.string(),
  }),
  folders: z.object({
    game: z.string(),
    skin: z.string(),
    songs: z.string(),
    beatmap: z.string(),
  }),
  files: z.object({
    beatmap: z.string(),
    background: z.string(),
    audio: z.string(),
  }),
  directPath: z.object({
    beatmapFile: z.string(),
    beatmapBackground: z.string(),
    beatmapAudio: z.string(),
    beatmapFolder: z.string(),
    skinFolder: z.string(),
  }),
  tourney: z.object({
    scoreVisible: z.boolean(),
    starsVisible: z.boolean(),
    ipcState: z.number(),
    bestOF: z.number(),
    team: z.object({
      left: z.string(),
      right: z.string(),
    }),
    points: z.object({
      left: z.number(),
      right: z.number(),
    }),
    chat: z.array(z.unknown()),
    totalScore: z.object({
      left: z.number(),
      right: z.number(),
    }),
    clients: z.array(z.unknown()),
  }),
});
